version: '3.8'

services:
  web:
    build: .
    # command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn grocery.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "ENVIRONMENT=development"
      - "SECRET_KEY=django-insecure-ok-g$$+c!nqu)$$!kv=pt14p6f@3qy)2_ln71(h7ubm9ti#fm)o1"
      - "DEBUG=1"
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgres_data:/home
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
volumes:
  postgres_data:
