# Generated by Django 3.2.4 on 2021-06-07 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('price_per_lb', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.item')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.store')),
            ],
        ),
    ]
